---
environments:
  dev:
    docker:
      APP: frontend
      VERSION: "0.1"
      registry: ecr
      url: 199920436475.dkr.ecr.us-east-1.amazonaws.com
      platforms: linux/amd64
      filename: Dockerfile  
      filepath: .
      arguments:
        APP: "{{ APP }}"
        VERSION: "{{ VERSION }}"
    
    microservice:
      cluster: dev-ecs_cluster
      cpu: 256
      memory: 256
      replicas: 1
      domain_name: frontend.dev.edeluquez.com
      variables:
        DATABASE: louvre
        USERNAME: admin
      secrets:
        PASSWORD: dev/db/fastapi/password
        ENDPOINT: dev/db/fastapi/endpoint