---
name: CICD MS Deploy
run-name: MS deploy

on:
  workflow_dispatch: 

jobs:
  setup-env:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: dev

    steps:
      - name: echo
        run: |
          echo "ENVIRONMENT=${{ vars.ENVIRONMENT }}"


  buildAndTestApp:
    needs: [setup-env]
    uses: emosquerafs/actions-templates/.github/workflows/buildAndTestApp.yml@main
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
      SONAR_TOKEN: 'sqa_c62ddabcdc20090d8fca922d97e896976260d38c'
      SONAR_HOST_URL: 'http://186.145.138.81:9000'
    
     

  build-and-push:
    needs: [setup-env, buildAndTestApp]
    uses: edelux/cicd-build-push/.github/workflows/build_push.yaml@main
    with:
      ENVIRONMENT: ${{ needs.setup-env.outputs.ENVIRONMENT }}

    permissions:
      id-token: write
      contents: read


  deploy-update-task:
    needs: [setup-env, build-and-push,buildAndTestApp]
    uses: edelux/cicd-ecs/.github/workflows/deploy_and_update_tasks.yaml@main
    with:
      ENVIRONMENT: ${{ needs.setup-env.outputs.ENVIRONMENT }}

    permissions:
      id-token: write
      contents: read
...